%padre(juan).
%padre(antonio).
%padre(luiso).
%padre(eduardo).
%madre(luisa).
%padrede(pedro,juan).
%padrede(juan,julio).
%padrede(juan,jose).
%madrede(luisa,maria).
%abuelo(X,Y):- padrede(X,W),padrede(W,Y).

%Hijos
hijo(josue).
hijo(fernando).
hijo(leonardo).
hijo(sebastian).
hijo(christian).
hijo(luis).
hijo(santos).
hijo(cesar).
hijo(saul).
hijo(rafael).
hijo(omar).
hijo(edgar).
hijo(saulito).
hijo(daniel).
hijo(rafaeljr).
hijo(santiago).
hijo(dilan).
%hijas
hija(ana).
hija(fernanda).
hija(anabel).
hija(natalia).
hija(dayana).
hija(areli).
hija(atziri).
hija(elizabeth).
hija(linete).
hija(lizete).
hija(mia).
hija(mariel).
hija(esther).
hija(noemi).
hija(margarita).
hija(juanita).
hija(merced).
%padres
padrede(fernando,josue).
padrede(fernando,fernanda).
padrede(mises,leonardo).
padrede(rafa2,sebastian).
padrede(desconocido,christian).
padrede(desconocido,dayana).
padrede(bisabuelo,luis).
padrede(santos,cesar).
padrede(santos,saul).
padrede(santos,rafael).
padrede(santos,omar).
padrede(santos,anabel).
padrede(luis,fernando).
padrede(luis,noemi).
padrede(luis,margarita).
padrede(luis,esther).
padrede(cesar,santiago).
padrede(cesar,mariel).
padrede(rafael,daniel).
padrede(rafael,rafaeljr).
padrede(rafael,mia).
padrede(saul,dilan).
padrede(saul,edgar).
padrede(saul,saulito).
padrede(omar,areli).
padrede(omar,atziri).
padrede(omar,elizabeth).
%Madres
madrede(anabel,josue).
madrede(anabel,fernanda).
madrede(juanita,fernando).
madrede(juanita,esther).
madrede(juanita,margarita).
madrede(juanita,noemi).
madrede(ana,anabel).
madrede(ana,saul).
madrede(ana,cesar).
madrede(ana,omar).
madrede(ana,rafael).
madrede(noemi,natalia).
madrede(esther,leonardo).
madrede(margarita,christian).
madrede(margarita,dayana).
madrede(margarita,sebastian).
madrede(merced,santiago).
madrede(merced,mariel).
